version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-^*rf%+gh(o1xip2@hg&tss^x7v!1a!r=on_$)@(nkxrzm!(n5i
      - CLOUD_NAME=dr7mqzlf9
      - CLOUD_API_KEY=931525198692321
      - CLOUD_API_SECRET=AqcRuZrFthzijMTJrjugtl-dH3o

volumes:
  postgres_data: