# Generated by Django 4.2 on 2023-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='movies_images')),
            ],
        ),
    ]
