# Generated by Django 4.2 on 2023-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_movie_thing_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
