# Generated by Django 4.2.1 on 2024-02-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_anime_genre_remove_comment_thing_delete_thing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='api.genre'),
        ),
    ]
